// <auto-generated />
using System;
using Hotel.ATR.Portal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hotel.ATR.Portal.Migrations
{
    [DbContext(typeof(HotelAtrContext))]
    partial class HotelAtrContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Hotel.ATR.Portal.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("PathToImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathToImgHover")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoomDataid")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomDataid");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Hotel.ATR.Portal.Models.Room", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PathToImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("RoomDataid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("RoomDataid");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Hotel.ATR.Portal.Models.RoomData", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.HasKey("id");

                    b.ToTable("RoomData");
                });

            modelBuilder.Entity("Hotel.ATR.Portal.Models.Client", b =>
                {
                    b.HasOne("Hotel.ATR.Portal.Models.RoomData", null)
                        .WithMany("Clients")
                        .HasForeignKey("RoomDataid");
                });

            modelBuilder.Entity("Hotel.ATR.Portal.Models.Room", b =>
                {
                    b.HasOne("Hotel.ATR.Portal.Models.RoomData", null)
                        .WithMany("Rooms")
                        .HasForeignKey("RoomDataid");
                });

            modelBuilder.Entity("Hotel.ATR.Portal.Models.RoomData", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
